//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutcoldSolutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InversionOfControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InversionOfControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutcoldSolutions.InversionOfControlResources", typeof(InversionOfControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find constructor for type &apos;{0}&apos;. If type has more than one constructor - use InjectAttribute to mark the constructor which you want to use for injection..
        /// </summary>
        internal static string ErrMsg_CannotFindConstructorForType {
            get {
                return ResourceManager.GetString("ErrMsg_CannotFindConstructorForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set interface or abstract class &apos;{0}&apos; as an implementation type..
        /// </summary>
        internal static string ErrMsg_CannotSetInterfaceAsImplementation {
            get {
                return ResourceManager.GetString("ErrMsg_CannotSetInterfaceAsImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set more than one behavior for registration..
        /// </summary>
        internal static string ErrMsg_CannotSetMoreThanOneBehavior {
            get {
                return ResourceManager.GetString("ErrMsg_CannotSetMoreThanOneBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set type &apos;{0}&apos; as implementation because the registered type &apos;{1}&apos; cannot be assignable from it..
        /// </summary>
        internal static string ErrMsg_CannotSetTypeAsImplementation {
            get {
                return ResourceManager.GetString("ErrMsg_CannotSetTypeAsImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is disposed..
        /// </summary>
        internal static string ErrMsg_ContainerDisposed {
            get {
                return ResourceManager.GetString("ErrMsg_ContainerDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container with context &apos;{0}&apos; is disposed..
        /// </summary>
        internal static string ErrMsg_ContainerDisposedContext {
            get {
                return ResourceManager.GetString("ErrMsg_ContainerDisposedContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container is not in registration mode. User Register() method to block container for registration..
        /// </summary>
        internal static string ErrMsg_ContainerIsNotBlockedForRegistration {
            get {
                return ResourceManager.GetString("ErrMsg_ContainerIsNotBlockedForRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type when container is locked by IRegistrationContext..
        /// </summary>
        internal static string ErrMsg_ContainerLocked {
            get {
                return ResourceManager.GetString("ErrMsg_ContainerLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation is not specified for interface or abstract class &apos;{0}&apos;..
        /// </summary>
        internal static string ErrMsg_ImplementationIsNotSpecifiedForInterface {
            get {
                return ResourceManager.GetString("ErrMsg_ImplementationIsNotSpecifiedForInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If container instance has more than one registered type it should has the specified implementation type..
        /// </summary>
        internal static string ErrMsg_MoreThanTwoTypesShouldHaveImplementationType {
            get {
                return ResourceManager.GetString("ErrMsg_MoreThanTwoTypesShouldHaveImplementationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous created registration context is not disposed..
        /// </summary>
        internal static string ErrMsg_PreviosCreatedContextIsNotDisposed {
            get {
                return ResourceManager.GetString("ErrMsg_PreviosCreatedContextIsNotDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not registered..
        /// </summary>
        internal static string ErrMsg_TypeIsNotRegistered {
            get {
                return ResourceManager.GetString("ErrMsg_TypeIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown container..
        /// </summary>
        internal static string ErrMsg_UnknownContainer {
            get {
                return ResourceManager.GetString("ErrMsg_UnknownContainer", resourceCulture);
            }
        }
    }
}
