//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutcoldSolutions.Diagnostics {
    using System;
    using System.Reflection;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjectReleaseVerificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectReleaseVerificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutcoldSolutions.Diagnostics.ObjectReleaseVerificationResources", typeof(ObjectReleaseVerificationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ---- Alive Objects Count: {0} ----
        ///.
        /// </summary>
        internal static string AliveObjectsEnd {
            get {
                return ResourceManager.GetString("AliveObjectsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ---- Alive Objects ----.
        /// </summary>
        internal static string AliveObjectsTitle {
            get {
                return ResourceManager.GetString("AliveObjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context cannot be empty..
        /// </summary>
        internal static string ErrMsg_ContextCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrMsg_ContextCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Additional Info: {0}.
        /// </summary>
        internal static string ObjectInfo_AdditionalInfo {
            get {
                return ResourceManager.GetString("ObjectInfo_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Context: {0}.
        /// </summary>
        internal static string ObjectInfo_Context {
            get {
                return ResourceManager.GetString("ObjectInfo_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Is Alive: {0}.
        /// </summary>
        internal static string ObjectInfo_IsAlive {
            get {
                return ResourceManager.GetString("ObjectInfo_IsAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Object: {0}.
        /// </summary>
        internal static string ObjectInfo_Object {
            get {
                return ResourceManager.GetString("ObjectInfo_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Tracking Started Date: {0}.
        /// </summary>
        internal static string ObjectInfo_TrackingStartedDate {
            get {
                return ResourceManager.GetString("ObjectInfo_TrackingStartedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Type: {0}.
        /// </summary>
        internal static string ObjectInfo_Type {
            get {
                return ResourceManager.GetString("ObjectInfo_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ----.
        /// </summary>
        internal static string Output_Separator {
            get {
                return ResourceManager.GetString("Output_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ---- Released Objects Count: {0} ----.
        /// </summary>
        internal static string ReleasedObjectsEnd {
            get {
                return ResourceManager.GetString("ReleasedObjectsEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ---- Released Objects ----.
        /// </summary>
        internal static string ReleasedObjectsTitle {
            get {
                return ResourceManager.GetString("ReleasedObjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Object Release Verifier: Verification Failed. ({0}) ----.
        /// </summary>
        internal static string VerificationFailedTitle {
            get {
                return ResourceManager.GetString("VerificationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Object Release Verifier: Verification Succeeded. ({0}) ----.
        /// </summary>
        internal static string VerificationSuccededTitle {
            get {
                return ResourceManager.GetString("VerificationSuccededTitle", resourceCulture);
            }
        }
    }
}
